#ejercicio 1
# lista_super = ["tomate", "fideos", "arvejas", "detergente", "jabón", "alcohol"]
# try:
#     lista_super + "arroz"
# except:
#     print("no puedo agregar arroz")

#el uso del try...except no es correcto. Cuando se usa el except, en la misma
#linea tiene que especificar el tipo de error que puede llegar a surgir.
#lo modificaria agregando un "TypeError" al lado del except


#ejercicio 2 
# Definir una función que tenga como parámetros una lista de números por un lado y un número por otro y devuelva 
# una lista con la división de cada elemento por el número dado. Por ejemplo, si le paso ([2,4,6,8], 2), debería retornar [1,2,3,4]. 
# Tomar las precauciones necesarias.

# valores = int(input("ingresar la cantidad de valores que se van a introducir: "))
# lista1 = ""

# for i in range(int(valores)):
#     lista1 = [int(input("insertar un numero: "))]


# numero = int(input("insertar el numero por el cual quiere dividir todos los elementos: "))

# def division (lista1, numero):
#     try:
#         return lista1/numero
#     except ZeroDivisionError:
#         print("no se puede dividir por 0")






    